language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env :
        - SDL_MAJOR_VERSION=1
        - ADDRESSING_MODE=direct
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env :
        - SDL_MAJOR_VERSION=1
        - ADDRESSING_MODE=banks
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env :
        - SDL_MAJOR_VERSION=2
        - ADDRESSING_MODE=direct
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env :
        - SDL_MAJOR_VERSION=2
        - ADDRESSING_MODE=banks

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libgtk2.0-dev
      - libsdl2-dev

script:
  - ERR_CODE=0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cd BasiliskII/src/Unix;
        NO_CONFIGURE=1 ./autogen.sh;
        if [[ $SDL_MAJOR_VERSION == *"1"* ]]; then
            ./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon --enable-addressing=$ADDRESSING_MODE;
            make -j 4 || ERR_CODE=$?;
        else
            ./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon --with-sdl2 --enable-addressing=$ADDRESSING_MODE;
            make -j 4 || ERR_CODE=$?;
        fi
    fi
  - (exit $ERR_CODE)
